#pragma once

struct Camera;
struct DeathEvent;
struct Explosion;
struct HUD;
struct Invincibility;
struct Monitor;
struct Music;
struct Ring;
struct StageSetup;
struct TitleCard;
struct Player;
struct BlueShield;
struct RotatePalette;

#include "SonicNexus.hpp"
#include "NexusGlobals\Camera.hpp"
#include "NexusGlobals\DeathEvent.hpp"
#include "NexusGlobals\Explosion.hpp"
#include "NexusGlobals\HUD.hpp"
#include "NexusGlobals\Invincibility.hpp"
#include "NexusGlobals\Monitor.hpp"
#include "NexusGlobals\Music.hpp"
#include "NexusGlobals\Ring.hpp"
#include "NexusGlobals\StageSetup.hpp"
#include "NexusGlobals\TitleCard.hpp"
#include "Players\Player.hpp"
#include "SSZ\BlueShield.hpp"
#include "SSZ\RotatePalette.hpp"
