#pragma once

struct ActFinish;
struct Camera;
struct DeathEvent;
struct Explosion;
struct HUD;
struct Invincibility;
struct Monitor;
struct Music;
struct PSwitch;
struct Ring;
struct SignPost;
struct Spikes;
struct Spring;
struct StageSetup;
struct StarPost;
struct TitleCard;
struct Intro;
struct RLogo;
struct FadeUp;
struct Island;
struct Logo;
struct PressStart;
struct Player;
struct BlueShield;
struct Bridge;
struct Chompy;
struct CLedge;
struct Corkscrew;
struct Fan;
struct FrogOmatic;
struct HelliBomber;
struct MRally;
struct Parachute;
struct Platform;
struct RotatePalette;
struct SwingPlat;
struct TubeSwitch;
struct ZipLine;
struct ZipTrack;

#include "SonicNexus.hpp"
#include "Math.hpp"
#include "NexusGlobals\ActFinish.hpp"
#include "NexusGlobals\Camera.hpp"
#include "NexusGlobals\DeathEvent.hpp"
#include "NexusGlobals\Explosion.hpp"
#include "NexusGlobals\HUD.hpp"
#include "NexusGlobals\Invincibility.hpp"
#include "NexusGlobals\Monitor.hpp"
#include "NexusGlobals\Music.hpp"
#include "NexusGlobals\PSwitch.hpp"
#include "NexusGlobals\Ring.hpp"
#include "NexusGlobals\SignPost.hpp"
#include "NexusGlobals\Spikes.hpp"
#include "NexusGlobals\Spring.hpp"
#include "NexusGlobals\StageSetup.hpp"
#include "NexusGlobals\StarPost.hpp"
#include "NexusGlobals\TitleCard.hpp"
#include "NexusIntro\Intro.hpp"
#include "NexusIntro\RLogo.hpp"
#include "NexusTitle\FadeUp.hpp"
#include "NexusTitle\Island.hpp"
#include "NexusTitle\Logo.hpp"
#include "NexusTitle\PressStart.hpp"
#include "Players\Player.hpp"
#include "SSZ\BlueShield.hpp"
#include "SSZ\Bridge.hpp"
#include "SSZ\Chompy.hpp"
#include "SSZ\CLedge.hpp"
#include "SSZ\Corkscrew.hpp"
#include "SSZ\Fan.hpp"
#include "SSZ\FrogOmatic.hpp"
#include "SSZ\HelliBomber.hpp"
#include "SSZ\MRally.hpp"
#include "SSZ\Parachute.hpp"
#include "SSZ\Platform.hpp"
#include "SSZ\RotatePalette.hpp"
#include "SSZ\SwingPlat.hpp"
#include "SSZ\TubeSwitch.hpp"
#include "SSZ\ZipLine.hpp"
#include "SSZ\ZipTrack.hpp"
