#pragma once

struct ActFinish;
struct Camera;
struct DeathEvent;
struct Explosion;
struct HUD;
struct Invincibility;
struct Monitor;
struct Music;
struct PSwitch;
struct Ring;
struct SignPost;
struct Spikes;
struct Spring;
struct StageSetup;
struct StarPost;
struct TitleCard;
struct Player;
struct BlueShield;
struct Bridge;
struct Corkscrew;
struct Platform;
struct RotatePalette;
struct SwingPlat;
struct TubeSwitch;
struct ZipLine;
struct ZipTrack;

#include "SonicNexus.hpp"
#include "Math.hpp"
#include "NexusGlobals\ActFinish.hpp"
#include "NexusGlobals\Camera.hpp"
#include "NexusGlobals\DeathEvent.hpp"
#include "NexusGlobals\Explosion.hpp"
#include "NexusGlobals\HUD.hpp"
#include "NexusGlobals\Invincibility.hpp"
#include "NexusGlobals\Monitor.hpp"
#include "NexusGlobals\Music.hpp"
#include "NexusGlobals\PSwitch.hpp"
#include "NexusGlobals\Ring.hpp"
#include "NexusGlobals\SignPost.hpp"
#include "NexusGlobals\Spikes.hpp"
#include "NexusGlobals\Spring.hpp"
#include "NexusGlobals\StageSetup.hpp"
#include "NexusGlobals\StarPost.hpp"
#include "NexusGlobals\TitleCard.hpp"
#include "Players\Player.hpp"
#include "SSZ\BlueShield.hpp"
#include "SSZ\Bridge.hpp"
#include "SSZ\Corkscrew.hpp"
#include "SSZ\Platform.hpp"
#include "SSZ\RotatePalette.hpp"
#include "SSZ\SwingPlat.hpp"
#include "SSZ\TubeSwitch.hpp"
#include "SSZ\ZipLine.hpp"
#include "SSZ\ZipTrack.hpp"
