set(GENERATED_SOURCES
	${GAME_NAME}/Objects/NexusGlobals/ActFinish.cpp
	${GAME_NAME}/Objects/NexusGlobals/Camera.cpp
	${GAME_NAME}/Objects/NexusGlobals/DeathEvent.cpp
	${GAME_NAME}/Objects/NexusGlobals/Explosion.cpp
	${GAME_NAME}/Objects/NexusGlobals/HUD.cpp
	${GAME_NAME}/Objects/NexusGlobals/Invincibility.cpp
	${GAME_NAME}/Objects/NexusGlobals/Monitor.cpp
	${GAME_NAME}/Objects/NexusGlobals/Music.cpp
	${GAME_NAME}/Objects/NexusGlobals/PSwitch.cpp
	${GAME_NAME}/Objects/NexusGlobals/Ring.cpp
	${GAME_NAME}/Objects/NexusGlobals/SignPost.cpp
	${GAME_NAME}/Objects/NexusGlobals/Spikes.cpp
	${GAME_NAME}/Objects/NexusGlobals/Spring.cpp
	${GAME_NAME}/Objects/NexusGlobals/StageSetup.cpp
	${GAME_NAME}/Objects/NexusGlobals/StarPost.cpp
	${GAME_NAME}/Objects/NexusGlobals/TitleCard.cpp
	${GAME_NAME}/Objects/NexusIntro/Intro.cpp
	${GAME_NAME}/Objects/NexusIntro/RLogo.cpp
	${GAME_NAME}/Objects/NexusTitle/FadeUp.cpp
	${GAME_NAME}/Objects/NexusTitle/Island.cpp
	${GAME_NAME}/Objects/NexusTitle/Logo.cpp
	${GAME_NAME}/Objects/NexusTitle/PressStart.cpp
	${GAME_NAME}/Objects/Players/Player.cpp
	${GAME_NAME}/Objects/SSZ/BlueShield.cpp
	${GAME_NAME}/Objects/SSZ/Bridge.cpp
	${GAME_NAME}/Objects/SSZ/Chompy.cpp
	${GAME_NAME}/Objects/SSZ/CLedge.cpp
	${GAME_NAME}/Objects/SSZ/Corkscrew.cpp
	${GAME_NAME}/Objects/SSZ/Fan.cpp
	${GAME_NAME}/Objects/SSZ/FrogOmatic.cpp
	${GAME_NAME}/Objects/SSZ/HelliBomber.cpp
	${GAME_NAME}/Objects/SSZ/MRally.cpp
	${GAME_NAME}/Objects/SSZ/Parachute.cpp
	${GAME_NAME}/Objects/SSZ/Platform.cpp
	${GAME_NAME}/Objects/SSZ/RotatePalette.cpp
	${GAME_NAME}/Objects/SSZ/SwingPlat.cpp
	${GAME_NAME}/Objects/SSZ/TubeSwitch.cpp
	${GAME_NAME}/Objects/SSZ/ZipLine.cpp
	${GAME_NAME}/Objects/SSZ/ZipTrack.cpp
)